version: 2
updates:
  # App dependencies updates (Node.js)
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
