version: 2
updates:
  # App dependencies updates (Node.js)
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"  # Restrict updates to direct dependencies only

      
  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
