name: Security Vulnerability Report
description: Report a security vulnerability that needs attention
title: "VULN-[Package]-[CVE]"
labels: ["security", "vulnerability"]
assignees:
  - security-team

body:
  - type: markdown
    attributes:
      value: |
        ## Security Vulnerability Details
        Please provide information about the detected vulnerability.

  - type: input
    id: package
    attributes:
      label: Affected Package
      description: Name of the vulnerable package
      placeholder: "e.g., cross-spawn"
    validations:
      required: true

  - type: input
    id: cve
    attributes:
      label: CVE ID
      description: CVE identifier if available
      placeholder: "e.g., CVE-2024-21538"
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the vulnerability and its potential impact
    validations:
      required: true

  - type: textarea
    id: remediation
    attributes:
      label: Remediation Steps
      description: Steps to fix or mitigate the vulnerability
      placeholder: |
        1. Update package to version X
        2. Apply security patch
        3. Implement workaround
    validations:
      required: true 